# Generated by Django 6.0.7 on 2026-08-13 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storesetting',
            name='festival_music_url',
        ),
    ]
