# Generated by Django 6.0.7 on 2026-08-12 20:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Video ka title', max_length=255)),
                ('thumbnail_url', models.URLField(help_text='Thumbnail Image Link')),
                ('video_url', models.URLField(help_text='Video streaming Source URL')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Colors yahan likhein comma laga kar (Jaise: Red, Blue, Black)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('trending', '🔥 Trending New Arrivals'), ('combo', '🎁 Exclusive Combos & Sets'), ('bestseller', '⭐ Our Best Sellers')], default='trending', help_text='Yeh product website ke kis hisse mein dikhana hai?', max_length=20),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='festival_music_url',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3', help_text='Yahan dashboard se koi bhi song URL paste karein', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='color_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='productcolor',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='color_variations', to='store.product'),
        ),
    ]
