# Generated by Django 6.0.7 on 2026-08-13 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_remove_storesetting_festival_music_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='storesetting',
            name='festival_music_url',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3', help_text='Yahan dashboard se koi bhi song URL paste karein', max_length=500, null=True),
        ),
    ]
