# Generated by Django 6.0.7 on 2026-08-12 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_videoreview_product_colors_product_section_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='VideoReview',
            new_name='StoreVideoReview',
        ),
        migrations.RemoveField(
            model_name='product',
            name='section',
        ),
        migrations.RemoveField(
            model_name='storesetting',
            name='festival_music_url',
        ),
        migrations.AddField(
            model_name='product',
            name='display_section',
            field=models.CharField(choices=[('trending', '🔥 Trending New Arrivals'), ('combo', '🎁 Exclusive Combos & Sets'), ('bestseller', '⭐ Our Best Sellers')], default='trending', help_text='Website ke kis hisse mein dikhana hai?', max_length=20),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='bg_music_link',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text='Banner ka naam', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Colors yahan likhein comma laga kar', max_length=255, null=True),
        ),
    ]
