# Generated by Django 6.0.7 on 2026-08-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_rename_videoreview_storevideoreview_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StoreVideoReview',
            new_name='VideoReview',
        ),
        migrations.RemoveField(
            model_name='product',
            name='display_section',
        ),
        migrations.RemoveField(
            model_name='storesetting',
            name='bg_music_link',
        ),
        migrations.AddField(
            model_name='product',
            name='section',
            field=models.CharField(choices=[('trending', 'ЁЯФе Trending New Arrivals'), ('combo', 'ЁЯОБ Exclusive Combos & Sets'), ('bestseller', 'тнР Our Best Sellers')], default='trending', help_text='Yeh product website ke kis hisse mein dikhana hai?', max_length=20),
        ),
        migrations.AddField(
            model_name='storesetting',
            name='festival_music_url',
            field=models.URLField(blank=True, default='https://cdn.pixabay.com/download/audio/2022/05/27/audio_1808fbf07a.mp3', help_text='Yahan dashboard se koi bhi song URL paste karein', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='title',
            field=models.CharField(help_text='Banner ka naam (jaise: Diwali Sale)', max_length=200),
        ),
        migrations.AlterField(
            model_name='product',
            name='colors',
            field=models.CharField(blank=True, help_text='Colors yahan likhein comma laga kar (Jaise: Red, Blue, Black)', max_length=255, null=True),
        ),
    ]
